# Markdownlint configuration
default: true

# Exclude virtual environment directories
exclude:
  - venv/
  - .venv/

# Allow HTML
MD033: false

# Allow inline HTML
MD010: false

# Line length
MD013:
  line_length: 100
  code_blocks: false
  tables: false

# Allow duplicate headers
MD024:
  siblings_only: true
